"""label_relations_and_source_term_link

Revision ID: 002
Revises: 001
Create Date: 2026-05-21 09:19:03.020518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '002'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_term_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_term_id', sa.Integer(), nullable=False),
    sa.Column('to_term_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_term_id'], ['source_term.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_term_id'], ['source_term.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_term_link_dataset_id'), 'source_term_link', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_source_term_link_from_term_id'), 'source_term_link', ['from_term_id'], unique=False)
    op.create_index(op.f('ix_source_term_link_to_term_id'), 'source_term_link', ['to_term_id'], unique=False)
    op.add_column('dataset', sa.Column('label_relations', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset', 'label_relations')
    op.drop_index(op.f('ix_source_term_link_to_term_id'), table_name='source_term_link')
    op.drop_index(op.f('ix_source_term_link_from_term_id'), table_name='source_term_link')
    op.drop_index(op.f('ix_source_term_link_dataset_id'), table_name='source_term_link')
    op.drop_table('source_term_link')
    # ### end Alembic commands ###

